### ISSUE TITLE
ipykernel ignore signals

### ISSUE THREAD

**Issue by Roffild** [ipython/ipykernel#946]
Runned as server in Docker:
```bash
$ kill -QUIT 1
$ kill -TERM 1
$ kill -KILL 1
$ ps
PID   USER     TIME  COMMAND
    1 usr       0:01 /usr/local/bin/python -m ipykernel --config=./ipykernel_conf.py
```
in docker-compose.yml:
```yml
services:
  ipykernel:
    command: ["/usr/local/bin/python", "-m", "ipykernel", "--config=./ipykernel_conf.py"]
    stop_signal: "SIGQUIT"
    stop_grace_period: "10s"
```

In my other script, I register a signal to break the loop. But I did not find this code in ipykernel.
```python
import signal
import time

ISRUN = True

def sighandler(signum, frame):
    global ISRUN
    ISRUN = False
signal.signal(signal.SIGTERM, sighandler)
signal.signal(signal.SIGQUIT, sighandler)

while ISRUN:
    time.sleep(1)
```
